### PR TITLE
Add agent model name to request query

### PR DESCRIPTION
**Pull request by Oceania2018**
localhost:5000/train?project=my_project&model=my_model_name

### CODE REVIEW

**Comment by paschmann** [comment]
@Oceania2018 - please validate why you need the agent name included in the request? Per the Rasa NLU HTTP API Docs, there is no param needed? https://www.rasa.com/docs/nlu/http/

**Comment by Oceania2018** [comment]
@paschmann Please see the note from [HTTP API Docs](https://www.rasa.com/docs/nlu/http/), "The server will automatically generate a name for the trained model. If you want to set the name yourself, call the endpoint using localhost:5000/train?project=my_project&**model=my_model_name**". Actually,  It's better if we change it to "&model=" + req.query.name, I just follow Rasa UI pattern, even it might not make sense.

I'm trying to make Rasa UI work with another bot engine [BotSharp](https://github.com/Oceania2018/BotSharp). It still work if you don't merge this change. But I noticed that Rasa UI already generated a model name from frontend. So I consider that we might use it.

**Comment by Oceania2018** [comment]
Do you want me change the 40th line `logRequest(req, "train", {project: req.query.project, agent: req.query.name, data: req.body});` to `logRequest(req, "train", {project: req.query.project, model: req.query.name, data: req.body});`

**Comment by paschmann** [comment]
@Oceania2018 - no, per the Rasa NLU HTTP API docs, this line should be model: https://github.com/paschmann/rasa-ui/pull/105/files#diff-9a38e7260de0e7afb6752be4607ed39cR53

**Comment by Oceania2018** [comment]
Current it's agent `logRequest(req, "train", {project: req.query.project, **agent**: req.query.name, data: req.body})`

**Comment by Oceania2018** [comment]
@paschmann Hi Paul, are you going to merge the pull request?

**Pull request merged**
