### PR TITLE
Upgrade chat console for rasa12

### PR DESCRIPTION
**Pull request by huberrom**
As I said, still working on it, so I put it as a WIP.

To clarify the code, I split your core_router class into two class. Most of the current code is in core_server_V10 (with the lastest update) and I put mine in core_server_V12 which is chose when the core version is > 11 

#132

### CODE REVIEW

**Comment by paschmann** [comment]
@pradeepmvn - do you have some experience with Rasa Core to check this PR?

**Comment by huberrom** [comment]
Change to WIP again since I need to use the correct model when calling (using the default one for the moment)

**Comment by pradeepmvn** [comment]
@paschmann Sure. This would be a major implementation change. We might need more time to test different componets and make sure both the versions are in good shape before we merge.
@huberrom Awesome work!! Can you please update once you are done. Will pull this and run some tests.

**Comment by pradeepmvn** [comment]
@huberrom Iam thinking should we even need rasa-ui to proxy rasa core requests for v12 and above? I think the bot can directly hit the rasa core end point and rasa-ui can piggyback on it for conversations and history.

**Comment by pradeepmvn** [comment]
@huberrom Makes sense. thanks Huberrom. I will merge into master. Thanks for your contribution.

**Pull request merged**
