### PR TITLE
WIP: Cbt 288 us merge with rasa ui

### PR DESCRIPTION
**Pull request by elvay1**
Still a work in progress,

This merge request address issues opened by @huberrom #145 #146 #147 #148 
There was quite few conflicts during the merge so we've got some more non regression test to perform.

We know it's a massive PR and we will try to be more incremental in the future!

### CODE REVIEW

**Comment by huberrom** [comment]
I'm checking the regression tests, but I think I'll have to open a new MR since he's in holidays

**Comment by huberrom** [comment]
@pradeepmvn Can you tell me which NLU version you are using ? In training.js, you add this :

```
 var dataToPost={rasa_nlu_pipeline:"",trainingData:exportData};
```

But it doesn't seems to work for me, I got the following error :

```
rasa_nlu_1       | ERROR:rasa_nlu.train:Failed to train project 'chatbot-masante'.
rasa_nlu_1       | Traceback (most recent call last):
rasa_nlu_1       |   File "/app/rasa_nlu/train.py", line 125, in do_train_in_worker
rasa_nlu_1       |     component_builder)
rasa_nlu_1       |   File "/app/rasa_nlu/train.py", line 153, in do_train
rasa_nlu_1       |     training_data = load_data(data, cfg.language)
rasa_nlu_1       |   File "/app/rasa_nlu/training_data/loading.py", line 55, in load_data
rasa_nlu_1       |     data_sets = [_load(f, language) for f in files]
rasa_nlu_1       |   File "/app/rasa_nlu/training_data/loading.py", line 55, in <listcomp>
rasa_nlu_1       |     data_sets = [_load(f, language) for f in files]
rasa_nlu_1       |   File "/app/rasa_nlu/training_data/loading.py", line 109, in _load
rasa_nlu_1       |     raise ValueError("Unknown data format for file {}".format(filename))
rasa_nlu_1       | ValueError: Unknown data format for file /tmp/tmpa86suks5_training_data
rasa_nlu_1       | 2019-02-04 14:20:37+0000 [-] 2019-02-04 14:20:37 WARNING  rasa_nlu.data_router  - [Failure instance: Traceback (failure with no frames): <class 'rasa_nlu.train.TrainingException'>: Unknown data format for file /tmp/tmpa86suks5_training_data
```

**Comment by huberrom** [comment]
You can close this PR, you can find the new fixed one at #151

**Comment by pradeepmvn** [comment]
Closing this.. will merge new pr #151

**Pull request closed without merging**
